{% set name = "sshfs" %}
{% set version = "2023.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sshfs-{{ version }}.tar.gz
  sha256: 8f63f83dd05511552f3ac9590212888dff70dfd43645615b5c030190d2fe3a2b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - asyncssh >=2.11.0,<3
    - fsspec >=2021.8.1
    - python >=3.8

test:
  imports:
    - sshfs
    - sshfs.pools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sshfs/
  summary: SSH Filesystem -- Async SSH/SFTP backend for fsspec
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isidentical
    - efiop
    - pmrowla
    - shcheklein
